### ISSUE TITLE
Stuck marines

### ISSUE THREAD

**Issue by Ronin4862** [SamVanheer/halflife-bs-updated#4] opened 2022-09-07 20:11 UTC
In "Captive Freight" the marines in the tunnel don't always initiate their attack:

https://youtu.be/SYfJDimfa9E

P.S. It seems that the AI is just plain dumb at times...the soldiers don't pursue you and just stand still and shoot you only if they see you. I have no explanation for that. The only workaround when that happens is to type "restart" in the console. That resets their AI.

**Comment by SamVanheer** [comment] 2022-09-14 19:55
Looks like that might be a node graph issue. Stand in the tunnel and enter the cheat command `impulse 197`. See if the game shows beam effects. It should show beams going from each grunt's spawn point to other nodes and then out towards the turret area.

If it doesn't, delete the node graph for that map (the `.nod` file in `maps/graphs`) and try the map again.

The AI is almost 24 years old, that's just how it works. That can't be fixed without a complete rewrite, which is way out of scope.

**Comment by Ronin4862** [comment] 2022-09-15 08:04
Fortunately it didn't happen again after I typed "restart" then.
If it does happen again I'll try what you said.

> If it doesn't, delete the node graph for that map (the `.nod` file in `maps/graphs`) and try the map again.

And the node graph would be rebuilt automatically after I start the game or do I have to reinstall BS-Updated?

**Comment by SamVanheer** [comment] 2022-09-16 09:46
Node graphs are automatically created if they don't exist, are older than the BSP file or if their version is older than the game's version.

**Comment by Ronin4862** [comment] 2022-09-16 22:37
It happened again. Deleting the node graph did nothing. Typing "restart" in the console and then loading my saved game again reset the AI.
https://youtu.be/OVz0pt3jbSg
https://youtu.be/3YyqEeiwabM

P.S. I must mention that I've rebuilt the dlls using your latest fix for the MP5 decals thing. Can this be the reason? Only this scene is affected. The AI in other scenes seems fine.
One other weird thing I noticed is after I get killed on the other side of the tunnel were the tank is, when the autosave kicks in, the left mouse button is unresponsive for about 1 second.

**Comment by SamVanheer** [comment] 2022-09-22 12:45
Impulse 197 should have shown connections in that tunnel. If there aren't any then the AI may be failing to find paths.

I haven't been able to reproduce the problem, though i have noticed NPCs misbehaving sometimes.

If you can find a way to reproduce the issue with unmodified Updated dlls then i can reproduce it and isolate the cause.

As for the mouse issue that's handled by the engine. There's probably an edge case that causes it to send mouse input to the main menu instead of the game. Nothing i can do about it, in any case.

**Comment by Ronin4862** [comment] 2022-09-22 13:30
> If you can find a way to reproduce the issue with unmodified Updated dlls then i can reproduce it and isolate the cause.

It happens only when I load a saved game that was saved while using a previous set of client.dll and hl.dll

To recap:
1. I used HLBSU beta 9 when I made the original save
2. You fixed the MP5 decals bug and then I built client.dll and hl.dll from your code.
3. This bug started to appear whenever I loaded that save (and it seems other saves aswell, such as Rosenberg in front of the old lab elevator entrance and not triggering his speech about his plans and refusing to follow you). BUT, whenever I've typed "restart" or replayed the map using "map xxxx" in the console everything worked fine.

I know you said saved games no longer work between releases, but in this particular case, in which I wanted to check you, the only solution was to build and replace the dlls that came with your Beta 9 with the code you released after fixing the MP5.

What I don't understand is why something so minor as fixing some weapon decals can break the AI of the entire game when loading a saved game. 

You can close the issue Sam.

**Comment by SamVanheer** [comment] 2022-09-22 13:42
> What I don't understand is why something so minor as fixing some weapon decals can break the AI of the entire game when loading a saved game.

It's probably because of this change:
https://github.com/SamVanheer/halflife-updated/commit/efacee0adad5c48fedbb290717c655cab0805d8d

This removed 2 fields from save/restore, so some save game data won't be interpreted correctly.

This is why i said that save games aren't compatible across commits. Any change can break them.

I'd suggest deleting all save games when using a new beta or making a new build yourself to avoid this in the future.

**Closed as completed by SamVanheer** 2022-09-22 13:42 UTC
Labels: invalid

**Comment by Ronin4862** [comment] 2022-09-22 14:03
> I'd suggest deleting all save games when using a new beta or making a new build yourself to avoid this in the future.

Not just after a new beta; after every new commit.
Having saved games helped me in the past to isolate specific issues and then report them to you.

99% percent of the time you find bugs just by playing and not looking for something specific. And when you play you save your game.

Whenever I'll find a new issue while casually playing I will double check by replaying the map again from zero (map xxx in the console).
